services:
  - type: web
    name: surebet-finder
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn pythonapp:app
    envVars:
      - key: API_KEY
        value: 644527349738df0ac9452e2a5f773afd